"""Porte verso l'infrastruttura (if-022 Repository)."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from typing import Protocol

from shotkeepr.core.domain.catalog import Session, Shot
from shotkeepr.core.domain.configuration import AppSettings


class SessionRepository(Protocol):
    def add(self, session: Session) -> None: ...
    def get(self, session_id: uuid.UUID) -> Session | None: ...
    def list(self) -> Sequence[Session]: ...
    def update(self, session: Session) -> None: ...


class ShotRepository(Protocol):
    def add_many(self, shots: Sequence[Shot]) -> None: ...
    def get(self, shot_id: uuid.UUID) -> Shot | None: ...
    def list_by_session(self, session_id: uuid.UUID) -> Sequence[Shot]: ...
    def find_by_hash(self, session_id: uuid.UUID, content_hash: str) -> Shot | None: ...


class SettingsRepository(Protocol):
    def load(self) -> AppSettings | None: ...
    def save(self, settings: AppSettings) -> None: ...


class SecretStoreUnavailableError(RuntimeError):
    """Nessun portachiavi utilizzabile nell'ambiente corrente."""


class SecretStore(Protocol):
    def get(self, ref: str) -> str | None: ...
    def set(self, ref: str, secret: str) -> None: ...
    def delete(self, ref: str) -> None: ...
