"""Porte verso l'infrastruttura (if-022 Repository)."""

from __future__ import annotations

import uuid
from collections.abc import Sequence
from typing import Protocol

from shotkeepr.core.domain.catalog import Session, Shot


class SessionRepository(Protocol):
    def add(self, session: Session) -> None: ...
    def get(self, session_id: uuid.UUID) -> Session | None: ...
    def list(self) -> Sequence[Session]: ...
    def update(self, session: Session) -> None: ...


class ShotRepository(Protocol):
    def add_many(self, shots: Sequence[Shot]) -> None: ...
    def get(self, shot_id: uuid.UUID) -> Shot | None: ...
    def list_by_session(self, session_id: uuid.UUID) -> Sequence[Shot]: ...
    def find_by_hash(self, session_id: uuid.UUID, content_hash: str) -> Shot | None: ...
