"""Porte verso l'infrastruttura (if-022 Repository)."""

from __future__ import annotations

import uuid
from collections.abc import Callable, Iterator, Sequence
from pathlib import Path
from typing import Protocol

from shotkeepr.core.domain.catalog import ExcludedFile, ImageFile, Session, Shot
from shotkeepr.core.domain.catalog.grouping import BurstGrouping
from shotkeepr.core.domain.catalog.review import ReviewStatus, ShotReview
from shotkeepr.core.domain.configuration import AppSettings
from shotkeepr.core.domain.models.model import ModelArtifact
from shotkeepr.core.domain.quality.exposure import ExposureMeasurement, ExposureMetrics
from shotkeepr.core.domain.quality.sharpness import SharpnessMeasurement, SharpnessMetrics


class SessionRepository(Protocol):
    def add(self, session: Session) -> None: ...
    def get(self, session_id: uuid.UUID) -> Session | None: ...
    def list(self) -> Sequence[Session]: ...
    def update(self, session: Session) -> None: ...


class ShotRepository(Protocol):
    def add_many(self, shots: Sequence[Shot]) -> None: ...
    def get(self, shot_id: uuid.UUID) -> Shot | None: ...
    def list_by_session(
        self,
        session_id: uuid.UUID,
        *,
        limit: int | None = None,
        offset: int = 0,
        group_id: uuid.UUID | None = None,
        ungrouped: bool = False,
    ) -> Sequence[Shot]: ...
    def count_by_session(
        self, session_id: uuid.UUID, *, group_id: uuid.UUID | None = None, ungrouped: bool = False
    ) -> int: ...
    def find_by_hash(self, session_id: uuid.UUID, content_hash: str) -> Shot | None: ...


class SettingsRepository(Protocol):
    def load(self) -> AppSettings | None: ...
    def save(self, settings: AppSettings) -> None: ...


class SecretStoreUnavailableError(RuntimeError):
    """Nessun portachiavi utilizzabile nell'ambiente corrente."""


class SecretStore(Protocol):
    def get(self, ref: str) -> str | None: ...
    def set(self, ref: str, secret: str) -> None: ...
    def delete(self, ref: str) -> None: ...


type DownloadProgress = Callable[[int, int], None]


class ModelStore(Protocol):
    def fetch(
        self, artifact: ModelArtifact, *, progress: DownloadProgress | None = None
    ) -> Path: ...
    def verify(self, artifact: ModelArtifact) -> Path: ...


class PhotoSource(Protocol):
    def validate_folder(self, folder: Path) -> Path: ...
    def scan(self, folder: Path, *, recursive: bool) -> Iterator[Path | ExcludedFile]: ...
    def inspect(self, path: Path) -> ImageFile: ...


class PreviewStore(Protocol):
    def validate_destination(self, source: Path) -> None: ...
    def create(self, file: ImageFile) -> Path: ...
    def path_for(self, file: ImageFile) -> Path: ...


class CatalogWriter(Protocol):
    def validate_destination(self, source: Path) -> None: ...
    def save_import(self, session: Session, shots: Sequence[Shot]) -> None: ...


class ExposureRepository(Protocol):
    def get(self, shot_id: uuid.UUID) -> ExposureMeasurement | None: ...
    def get_many(self, shot_ids: Sequence[uuid.UUID]) -> dict[uuid.UUID, ExposureMeasurement]: ...
    def save(self, measurement: ExposureMeasurement) -> None: ...


class ExposureAnalyzer(Protocol):
    version: str

    def read(self, preview: Path) -> bytes: ...
    def measure(self, content: bytes) -> ExposureMetrics: ...


class ReviewRepository(Protocol):
    def get(self, shot_id: uuid.UUID) -> ShotReview | None: ...
    def get_many(self, shot_ids: Sequence[uuid.UUID]) -> dict[uuid.UUID, ShotReview]: ...
    def set_status(self, shot: Shot, status: ReviewStatus) -> ShotReview: ...


class XmpWriter(Protocol):
    def targets(self, shot: Shot) -> Sequence[Path]: ...
    def write(self, shot: Shot, review: ShotReview) -> Sequence[Path]: ...


class GroupingRepository(Protocol):
    def get(self, session_id: uuid.UUID) -> BurstGrouping: ...
    def regroup(self, session_id: uuid.UUID, gap_seconds: float) -> BurstGrouping: ...


class SharpnessRepository(Protocol):
    def get(self, shot_id: uuid.UUID) -> SharpnessMeasurement | None: ...
    def get_many(self, shot_ids: Sequence[uuid.UUID]) -> dict[uuid.UUID, SharpnessMeasurement]: ...
    def save(self, measurement: SharpnessMeasurement) -> None: ...


class SharpnessAnalyzer(Protocol):
    version: str

    def read(self, preview: Path) -> bytes: ...
    def measure(self, content: bytes) -> SharpnessMetrics: ...
