"""schema iniziale

Revision ID: 0001
Revises:
Create Date: 2026-09-28 21:47:45.060682
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("genre", sa.String(length=60), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
        sa.UniqueConstraint("name", name=op.f("uq_profiles_name")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_folder", sa.String(length=4096), nullable=False),
        sa.Column("include_subfolders", sa.Boolean(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("checkpoint", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["profiles.id"], name=op.f("fk_sessions_profile_id_profiles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "excluded_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("reason", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_excluded_files_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_excluded_files")),
    )
    with op.batch_alter_table("excluded_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_excluded_files_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "group_corrections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=True),
        sa.Column("from_group", sa.Uuid(), nullable=True),
        sa.Column("to_group", sa.Uuid(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_group_corrections_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_corrections")),
    )
    with op.batch_alter_table("group_corrections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_corrections_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "selection_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("settings_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("acceptance_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_selection_runs_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_selection_runs")),
    )
    with op.batch_alter_table("selection_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_selection_runs_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "shot_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_shot_groups_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shot_groups")),
    )
    with op.batch_alter_table("shot_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shot_groups_session_id"), ["session_id"], unique=False)

    op.create_table(
        "shots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("capture_time", sa.DateTime(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["shot_groups.id"],
            name=op.f("fk_shots_group_id_shot_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_shots_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shots")),
        sa.UniqueConstraint("session_id", "content_hash", name=op.f("uq_shots_session_id")),
    )
    with op.batch_alter_table("shots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shots_group_id"), ["group_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shots_session_id"), ["session_id"], unique=False)

    op.create_table(
        "analysis_results",
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("analyzer_versions", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(), nullable=False),
        sa.Column("focus", sa.Float(), nullable=True),
        sa.Column("blur", sa.Float(), nullable=True),
        sa.Column("blur_type", sa.String(length=16), nullable=True),
        sa.Column("exposure", sa.Float(), nullable=True),
        sa.Column("highlights_clipped", sa.Float(), nullable=True),
        sa.Column("shadows_clipped", sa.Float(), nullable=True),
        sa.Column("noise", sa.Float(), nullable=True),
        sa.Column("aesthetic", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["shots.id"],
            name=op.f("fk_analysis_results_shot_id_shots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("shot_id", name=op.f("pk_analysis_results")),
    )
    op.create_table(
        "decisions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=8), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["selection_runs.id"],
            name=op.f("fk_decisions_run_id_selection_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"], ["shots.id"], name=op.f("fk_decisions_shot_id_shots"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("run_id", "shot_id", name=op.f("pk_decisions")),
    )
    op.create_table(
        "image_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=4096), nullable=False),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("camera_model", sa.String(length=120), nullable=True),
        sa.Column("camera_serial", sa.String(length=120), nullable=True),
        sa.Column("lens", sa.String(length=200), nullable=True),
        sa.Column("focal_mm", sa.Float(), nullable=True),
        sa.Column("exposure_s", sa.Float(), nullable=True),
        sa.Column("aperture", sa.Float(), nullable=True),
        sa.Column("iso", sa.Integer(), nullable=True),
        sa.Column("capture_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shot_id"], ["shots.id"], name=op.f("fk_image_files_shot_id_shots"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_files")),
    )
    with op.batch_alter_table("image_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_image_files_shot_id"), ["shot_id"], unique=False)

    op.create_table(
        "manual_status_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("old_status", sa.String(length=8), nullable=False),
        sa.Column("new_status", sa.String(length=8), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_manual_status_changes_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["shots.id"],
            name=op.f("fk_manual_status_changes_shot_id_shots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_status_changes")),
    )
    with op.batch_alter_table("manual_status_changes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_manual_status_changes_session_shot", ["session_id", "shot_id"], unique=False
        )

    op.create_table(
        "subjects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("bbox", sa.JSON(), nullable=False),
        sa.Column("head_bbox", sa.JSON(), nullable=True),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("eyes_open", sa.Boolean(), nullable=True),
        sa.Column("eyes_visible", sa.Boolean(), nullable=True),
        sa.Column("eyes_in_focus", sa.Boolean(), nullable=True),
        sa.Column("eyes_confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["analysis_results.shot_id"],
            name=op.f("fk_subjects_shot_id_analysis_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
    )
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subjects_shot_id"), ["shot_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subjects_shot_id"))

    op.drop_table("subjects")
    with op.batch_alter_table("manual_status_changes", schema=None) as batch_op:
        batch_op.drop_index("ix_manual_status_changes_session_shot")

    op.drop_table("manual_status_changes")
    with op.batch_alter_table("image_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_image_files_shot_id"))

    op.drop_table("image_files")
    op.drop_table("decisions")
    op.drop_table("analysis_results")
    with op.batch_alter_table("shots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shots_session_id"))
        batch_op.drop_index(batch_op.f("ix_shots_group_id"))

    op.drop_table("shots")
    with op.batch_alter_table("shot_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_groups_session_id"))

    op.drop_table("shot_groups")
    with op.batch_alter_table("selection_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_selection_runs_session_id"))

    op.drop_table("selection_runs")
    with op.batch_alter_table("group_corrections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_corrections_session_id"))

    op.drop_table("group_corrections")
    with op.batch_alter_table("excluded_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_excluded_files_session_id"))

    op.drop_table("excluded_files")
    op.drop_table("sessions")
    op.drop_table("profiles")
    # ### end Alembic commands ###
